### ISSUE TITLE
[1.14-19w11b] Crash on startup

### ISSUE THREAD

**Issue by The-Fireplace** [UpcraftLP/Realistic-Cobwebs#1]
https://paste.ubuntu.com/p/mQnYKJNXKN/

fabric-loader-0.3.7.109-19w11b.2
cobwebs-1.0.0

**Comment by UpcraftLP** [comment]
fixed in v[1.0.1](https://minecraft.curseforge.com/projects/250393files/2706418 "CurseForge")
