### ISSUE TITLE
Enchancement Fire Aspect Compatibility

### ISSUE THREAD

**Issue by TheTrueYak** [UpcraftLP/Realistic-Cobwebs#5]
Enchancement adds the ability for weapons with fire aspect to be used like a flint and steel would be, are there any plans for this functionality to be added to realistic cobwebs when Enchancement's config option for it is enabled?

![image](https://github.com/Up-Mods/Realistic-Cobwebs/assets/107325508/0a8c4d03-8d52-4f45-b3a4-0303e1e41d51)

**Comment by UpcraftLP** [comment]
I will look into it, if it's not too much work I can add it.

**Comment by UpcraftLP** [comment]
I added it as a separate option, independent of enchancement.
